### ISSUE TITLE
Can you provide a valid README for this project?

### ISSUE THREAD

**Issue by Initial-heart-1** [KomiMoe/LrcCloudmusic#4]
I found a copy of this project from Github and I noticed its description, which was interesting. But when I tried to find any more detailed and easy to read descriptions, I couldn't find anything.
If possible, would it be possible to provide some info to give a better understanding of it? 
Of course, if you don't want this, may I to apologies to you and close this issue.

**Comment by komimoe** [comment]
这个项目只是演示了如何在网易云PC客户端内存中找到当前行的歌词和进度。(for fun) (因为我觉得网易云客户端自带的歌词太难看了, 所以之后还打算写UI来着)

**Comment by Initial-heart-1** [comment]
> 这个项目只是演示了如何在网易云PC客户端内存中找到当前行的歌词和进度。(for fun) (因为我觉得网易云客户端自带的歌词太难看了, 所以之后还打算写UI来着)

wow，十分有趣。虽然不知道这是否违反网易云用户协议，但我想应该为这个项目添加一个“仅用于学习交流”的声明
期待出 UI，可能的话务必圈我一下 XD

**Comment by Initial-heart-1** [comment]
先把这个 issue 按
